### ISSUE TITLE
Would you like to share the four python crawler scripts that grab the event mentioned in your paper?

### ISSUE THREAD

**Issue by YuchaoZheng** [PyDL/cat-puma#1]
Thanks a lot.

**Comment by PyDL** [comment]
Sorry for the late reply. If you are interested in the relevant codes, please contact me via j.liu@qub.ac.uk Thanks.

**Comment by PyDL** [comment]
> Thanks a lot.

Sorry for the late reply. If you are interested in the relevant codes, please contact me via j.liu@qub.ac.uk Thanks.

**Comment by PyDL** [comment]
Closed
