### ISSUE TITLE
SyntaxError: invalid token 

### ISSUE THREAD

**Issue by MohamedNedal** [PyDL/cat-puma#2]
Hello, 
Can you please tell me how to fix this error? 
I was running the file: 

> code cat_puma_qt.py

 and I got an error at this line: 

line 211
    self.arrivevar.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 4, 14), QtCore.QTime(06, 50, 0)))
                                                                                         ^
SyntaxError: invalid token

and when I try to install the package "PyQt5" I get this error: 

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Collecting PyQt5
>   ERROR: Could not find a version that satisfies the requirement PyQt5 (from versions: none)
> ERROR: No matching distribution found for PyQt5

**Comment by PyDL** [comment]
Closed
